# Generated by Django 2.2.13 on 2020-07-06 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashborad', '0003_auto_20200707_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
