# Generated by Django 2.2.13 on 2020-07-06 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashborad', '0004_auto_20200707_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health',
            name='time',
        ),
    ]
