# Generated by Django 2.2.13 on 2020-07-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashborad', '0005_remove_health_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
