# Generated by Django 2.2.13 on 2020-07-07 01:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashborad', '0006_health_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 1, 18, 37, 381284)),
        ),
    ]
