# Generated by Django 2.2.13 on 2020-07-07 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashborad', '0007_auto_20200707_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health',
            name='time',
        ),
    ]
