# Generated by Django 2.2.13 on 2020-07-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashborad', '0012_auto_20200707_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyHeartRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HeartRate', models.IntegerField()),
                ('Hour', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyHealthSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AverageHeartRate', models.IntegerField()),
                ('AverageIntensity', models.IntegerField()),
                ('AverageSleep', models.IntegerField()),
                ('MinSleep', models.IntegerField()),
                ('MaxSleep', models.IntegerField()),
                ('MaxHearRate', models.IntegerField()),
            ],
        ),
    ]
