# Generated by Django 2.2.13 on 2020-07-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigIntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, db_column='Time', null=True)),
                ('value', models.IntegerField(blank=True, db_column='Value', null=True)),
                ('intensitytime', models.DateTimeField(blank=True, db_column='IntensityTime', null=True)),
                ('intensity', models.IntegerField(blank=True, db_column='Intensity', null=True)),
                ('stepsminute', models.DateTimeField(blank=True, db_column='StepsMinute', null=True)),
                ('steps', models.IntegerField(blank=True, db_column='Steps', null=True)),
                ('sleepminute', models.DateTimeField(blank=True, db_column='SleepMinute', null=True)),
                ('sleepvalue', models.IntegerField(blank=True, db_column='SleepValue', null=True)),
                ('sleeplogid', models.BigIntegerField(blank=True, db_column='SleepLogId', null=True)),
                ('metminute', models.DateTimeField(blank=True, db_column='MetMinute', null=True)),
                ('mets', models.IntegerField(blank=True, db_column='METs', null=True)),
                ('calminute', models.DateTimeField(blank=True, db_column='CalMinute', null=True)),
                ('calories', models.FloatField(blank=True, db_column='Calories', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HourlyHeartRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HeartRate', models.IntegerField()),
                ('Hour', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MinuteHeartRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyHealthSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AverageHeartRate', models.IntegerField()),
                ('AverageIntensity', models.IntegerField()),
                ('AverageSleep', models.IntegerField()),
                ('MinHeartRate', models.IntegerField()),
                ('MaxHeartRate', models.IntegerField()),
            ],
        ),
    ]
