# Generated by Django 2.2.13 on 2020-07-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='health',
            options={'managed': False},
        ),
    ]
